### ISSUE TITLE
Error when creating container

### ISSUE THREAD

**Issue by ghost** [spritsail/iodine#9]
Hi, trying to create a container using this image but I got this error:

Fatal: can't open lock file /run/xtables.lock: No such file or directory

Command used: `docker container run -p 53:53/udp --cap-add=NET_ADMIN --device /dev/net/tun -e IODINE_HOST=tunnel.example.com -e IODINE_PASS=12345 spritsail/iodine`

**I'm using my HOST** btw, not tunnel.example.com.

Tested on my Arch Linux and Ubuntu.

**Comment by Adam-Ant** [comment]
Thanks for bringing this to our attention.
 It seems to be related to a recent iptables update. Since we don't want or need to mount `/run` inside the container, a dummy folder will do just as well in this use case. I'll have a commit for this sorted in a few minutes.

Let us know if this is still an issue after the new build finishes.
